// <auto-generated />
using System;
using Dimchev.DiceRoller.Operative.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dimchev.DiceRoller.Operative.Infrastructure.Migrations
{
    [DbContext(typeof(DiceDbContext))]
    [Migration("20240926214004_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Dimchev.DiceRoller.Operative.Core.Models.DiceRollModel", b =>
                {
                    b.Property<Guid>("DiceRollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstDice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondDice")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("DiceRollId");

                    b.ToTable("DiceRolls");
                });
#pragma warning restore 612, 618
        }
    }
}
